### ISSUE TITLE
getting an error in labels.txt

### ISSUE THREAD

**Issue by ABZ1110** [yukkyo/voc2coco#13]
Hi, 
Hope you are doing great. 
I am tring to transfer .xml files to coco format, my labels is 
Not a target vesse and Target Vessel 
I get this error, your kind support plz

Start converting !
  0%|                                                   | 0/350 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "voc2coco.py", line 152, in <module>
    main()
  File "voc2coco.py", line 143, in main
    convert_xmls_to_cocojson(
  File "voc2coco.py", line 106, in convert_xmls_to_cocojson
    ann = get_coco_annotation_from_obj(obj=obj, label2id=label2id)
  File "voc2coco.py", line 62, in get_coco_annotation_from_obj
    assert label in label2id, f"Error: {label} is not in label2id !"
AssertionError: Error: Not a target vessel is not in label2id !

**Comment by venkeytii** [comment]
Did you manage to solve this?
